# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171207_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
