# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171207_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DateContract', models.DateField(auto_now_add=True)),
                ('CarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Car')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
