# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
