# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contract_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
